export const suits = {
    Heart2: 'Heart2',
    Heart3: 'Heart3',
    Heart4: 'Heart4',
    Heart5: 'Heart5',
    Heart6: 'Heart6',
    Heart7: 'Heart7',
    Heart8: 'Heart8',
    Heart9: 'Heart9',
    Heart10: 'Heart10',
    HeartJ: 'HeartJ',
    HeartQ: 'HeartQ',
    HeartK: 'HeartK',
    HeartA: 'HeartA',
    Spare2: 'Spare2',
    Spare3: 'Spare3',
    Spare4: 'Spare4',
    Spare5: 'Spare5',
    Spare6: 'Spare6',
    Spare7: 'Spare7',
    Spare8: 'Spare8',
    Spare9: 'Spare9',
    Spare10: 'Spare10',
    SpareJ: 'SpareJ',
    SpareQ: 'SpareQ',
    SpareK: 'SpareK',
    SpareA: 'SpareA',
    Diamond2: 'Diamond2',
    Diamond3: 'Diamond3',
    Diamond4: 'Diamond4',
    Diamond5: 'Diamond5',
    Diamond6: 'Diamond6',
    Diamond7: 'Diamond7',
    Diamond8: 'Diamond8',
    Diamond9: 'Diamond9',
    Diamond10: 'Diamond10',
    DiamondJ: 'DiamondJ',
    DiamondQ: 'DiamondQ',
    DiamondK: 'DiamondK',
    DiamondA: 'DiamondA',
    Club2: 'Club2',
    Club3: 'Club3',
    Club4: 'Club4',
    Club5: 'Club5',
    Club6: 'Club6',
    Club7: 'Club7',
    Club8: 'Club8',
    Club9: 'Club9',
    Club10: 'Club10',
    ClubJ: 'ClubJ',
    ClubQ: 'ClubQ',
    ClubK: 'ClubK',
    ClubA: 'ClubA',
} as const;

export type SuitsValues = typeof suits[keyof typeof suits];

export type Card = {
    value: number;
    suit: SuitsValues;
}